version: 2

workflows:
  version: 2
  release:
    jobs:
      - test
      - lint
      - build:
          requires:
            - test

jobs:
  test:
    working_directory: /go/src/github.com/miry/wattx_top_coins/
    docker:
      - image: circleci/golang:1.12-rc
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go get -v -t -d ./...
      - run: go generate pkg/version/base.go
      - run: go test ./... -v -race |& go-junit-report > $TEST_RESULTS/report.xml
      - store_test_results:
          path: /tmp/test-results

  lint:
    working_directory: /go/src/github.com/miry/wattx_top_coins
    docker:
      - image: circleci/golang:1.12-rc
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go get -v -t -d ./...
      - run: ./bin/lint

  build:
    environment:
      DOCKER_REPO: miry/top_coins
    docker:
      - image: circleci/golang:1.12-rc
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: ./bin/build
