---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: top_coins
    tier: web
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: top_coins
    tier: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: top_coins
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: top_coins
      tier: web
  template:
    metadata:
      labels:
        app: top_coins
        tier: web
    spec:
      containers:
        - name: web
          image: miry/top_coins:master
          ports:
            - containerPort: 8080
              name: http

          livenessProbe:
            httpGet:
              path: /version
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /version
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
            periodSeconds: 10
